"""
Example: AIGeneratorPlugin — offline unit tests.

These tests exercise the generator logic WITHOUT calling the AI API.
We mock the LLM client so the tests run in CI with no API key required.

Demonstrates:
  - Code extraction from markdown-fenced responses
  - File header injection
  - Output file writing
  - Error handling for empty responses
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from validrix.plugins.ai_generator import AITestGenerator, GenerationResult


class TestCodeExtraction:
    """Tests for _extract_code — the markdown parser."""

    def test_extracts_from_python_fence(self) -> None:
        """Handles ```python ... ``` fenced blocks."""
        raw = "Here is the code:\n```python\ndef test_foo():\n    pass\n```\n"
        result = AITestGenerator._extract_code(raw)
        assert "def test_foo():" in result

    def test_extracts_from_generic_fence(self) -> None:
        """Handles ``` ... ``` without language tag."""
        raw = "```\ndef test_bar():\n    assert True\n```"
        result = AITestGenerator._extract_code(raw)
        assert "def test_bar():" in result

    def test_falls_back_to_raw_when_no_fence(self) -> None:
        """When no fence is present, the raw text is returned as-is."""
        raw = "def test_baz():\n    assert 1 + 1 == 2\n"
        result = AITestGenerator._extract_code(raw)
        assert "test_baz" in result

    def test_raises_on_empty_response(self) -> None:
        """Empty responses raise ValueError with a descriptive message."""
        with pytest.raises(ValueError, match="no extractable Python code"):
            AITestGenerator._extract_code("")

    def test_raises_on_whitespace_only_response(self) -> None:
        """Whitespace-only responses raise ValueError."""
        with pytest.raises(ValueError, match="no extractable Python code"):
            AITestGenerator._extract_code("   \n\n   ")


class TestFileHeader:
    """Tests for _add_file_header."""

    def test_header_contains_description(self) -> None:
        code = "def test_login(): pass"
        result = AITestGenerator._add_file_header(code, "Login page")
        assert "Login page" in result
        assert "AUTO-GENERATED by Validrix" in result

    def test_header_is_prepended_not_appended(self) -> None:
        code = "def test_login(): pass"
        result = AITestGenerator._add_file_header(code, "Login page")
        assert result.index("AUTO-GENERATED") < result.index("def test_login")


class TestGeneratorIntegration:
    """Integration tests with mocked LLM client."""

    MOCK_CODE = textwrap.dedent("""\
        ```python
        import pytest

        class TestLogin:
            def test_valid_login(self, page):
                \"\"\"Verify valid login redirects to dashboard.\"\"\"
                page.goto("/login")
                page.locator("#email").fill("user@example.com")
                page.locator("#submit").click()
                assert page.url.endswith("/dashboard")
        ```
    """)

    def _make_generator(self) -> AITestGenerator:
        """Return a AITestGenerator with a mocked LLM client."""
        gen = AITestGenerator.__new__(AITestGenerator)
        gen._ai_config = MagicMock()
        gen._client = MagicMock()
        gen._client.complete.return_value = self.MOCK_CODE
        return gen

    def test_generate_returns_result_with_code(self) -> None:
        gen = self._make_generator()
        result = gen.generate("Login page")

        assert isinstance(result, GenerationResult)
        assert "test_valid_login" in result.code
        assert result.saved_path is None  # no output_path provided

    def test_generate_writes_file_when_output_path_given(
        self, tmp_path: Path
    ) -> None:
        gen = self._make_generator()
        output = tmp_path / "tests" / "test_login.py"

        result = gen.generate("Login page", output_path=output)

        assert result.saved_path == output
        assert output.exists()
        assert "test_valid_login" in output.read_text()

    def test_generate_creates_parent_directories(self, tmp_path: Path) -> None:
        gen = self._make_generator()
        deep_path = tmp_path / "a" / "b" / "c" / "test_deep.py"

        gen.generate("Feature", output_path=deep_path)

        assert deep_path.exists()


