from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

import pytest

import validrix.web_agent.test_generator as generator_module
from validrix.core.config_manager import AIConfig, FrameworkConfig
from validrix.web_agent.models import (
    AnalysisOptions,
    AnalyzeRequest,
    ButtonElement,
    CrawlResult,
    FormElement,
    FormField,
    ImageElement,
    JobStatus,
    LinkElement,
    TestSuiteResult,
)
from validrix.web_agent.test_generator import (
    WebTestGenerator,
    _add_file_header,
    _build_crawl_summary,
    _build_user_prompt,
    _call_anthropic,
    _call_openai,
    _extract_code,
    _infer_test_type,
    _parse_tests_from_code,
)


def _capture_write(writes: dict[str, str], path: Path, content: str) -> int:
    writes[str(path)] = content
    return len(content)


def test_models_properties_and_validation() -> None:
    crawl = CrawlResult(url="https://example.com")
    assert crawl.succeeded is True
    assert CrawlResult(url="https://example.com", error="boom").succeeded is False

    result = TestSuiteResult(
        url="https://example.com",
        prompt="goal",
        total_tests=2,
        passed=1,
        failed=1,
    )
    assert result.pass_rate == 0.5
    assert result.health_label == "degraded"
    assert TestSuiteResult(url="x", prompt="p").health_label == "untested"
    assert TestSuiteResult(url="x", prompt="p", total_tests=1, passed=1).health_label == "healthy"
    assert TestSuiteResult(url="x", prompt="p", total_tests=2, passed=0, failed=2).health_label == "critical"

    request = AnalyzeRequest(url="https://example.com/", prompt="check form")
    assert request.url == "https://example.com"
    with pytest.raises(ValueError, match="url must start"):
        AnalyzeRequest(url="example.com", prompt="check form")

    opts = AnalysisOptions()
    status = JobStatus(job_id="1", status="queued")
    assert opts.max_tests == 10
    assert status.progress == 0

    assert ButtonElement(text="Submit", selector="#submit").element_type == "button"
    assert FormField(name="email").field_type == "text"
    assert FormElement(selector="form").method == "get"
    assert LinkElement(text="Home", href="/").is_external is False
    assert ImageElement(src="/x.png").alt == ""


def test_generator_helpers_cover_prompt_building_and_parsing() -> None:
    crawl = CrawlResult(
        url="https://example.com",
        title="Example",
        meta_description="desc",
        headings=["Heading"],
        buttons=[ButtonElement(text="Submit", selector="#submit")],
        forms=[
            FormElement(
                selector="form",
                fields=[
                    FormField(
                        name="email",
                        field_type="email",
                        is_required=True,
                    )
                ],
            )
        ],
        links=[
            LinkElement(text="About", href="https://example.com/about"),
            LinkElement(
                text="Ext",
                href="https://other.com",
                is_external=True,
            ),
        ],
        images=[ImageElement(src="/x.png")],
        visible_text_sample="hello world",
    )

    summary = _build_crawl_summary(crawl)
    assert "PAGE URL" in summary
    assert "BUTTONS" in summary
    assert "INTERNAL LINKS" in summary

    prompt = _build_user_prompt(crawl, "test it", 3)
    assert "MAX_TESTS: 3" in prompt
    assert "test it" in prompt

    assert _extract_code("```python\nprint('x')\n```") == "print('x')"
    assert _extract_code("print('x')") == "print('x')"
    with pytest.raises(ValueError):
        _extract_code("   ")

    header = _add_file_header("code", "https://example.com", "goal")
    assert "AUTO-GENERATED by Validrix Web Agent" in header

    code = """
import pytest
from playwright.sync_api import Page, expect

BASE_URL = "https://example.com"

@pytest.mark.smoke
def test_submit_form(page: Page) -> None:
    \"\"\"Submits the form.\"\"\"
    page.goto(BASE_URL)

def helper() -> None:
    pass
"""
    tests = _parse_tests_from_code(code)
    assert tests[0].name == "test_submit_form"
    assert tests[0].description == "Submits the form."
    assert tests[0].test_type == "form"

    fallback = _parse_tests_from_code("def broken(")
    assert fallback[0].name == "test_generated_suite"

    assert _infer_test_type("test_nav_menu", "") == "navigation"
    assert _infer_test_type("test_alt_text", "") == "visual"
    assert _infer_test_type("test_a11y_tab", "") == "accessibility"
    assert _infer_test_type("test_other", "") == "functional"


def test_web_test_generator_generate_success_and_failures(monkeypatch: pytest.MonkeyPatch) -> None:
    writes: dict[str, str] = {}
    monkeypatch.setattr(generator_module.ConfigManager, "load", lambda: FrameworkConfig())
    monkeypatch.setattr(Path, "mkdir", lambda self, parents=False, exist_ok=False: None)
    monkeypatch.setattr(
        Path,
        "write_text",
        lambda self, content, encoding="utf-8": _capture_write(writes, self, content),
    )

    crawl = CrawlResult(url="https://example.com")
    generator = WebTestGenerator(ai_config=AIConfig())
    monkeypatch.setattr(
        generator,
        "_call_ai",
        lambda prompt: '```python\ndef test_ok(page: Page) -> None:\n    """ok"""\n    page.goto(BASE_URL)\n```',
    )

    suite = generator.generate(
        crawl=crawl,
        prompt="goal",
        max_tests=2,
        output_path=Path("generated.py"),
    )
    assert suite.succeeded is True
    assert len(suite.tests) == 1
    assert "generated.py" in writes

    failed_crawl = generator.generate(CrawlResult(url="https://example.com", error="boom"), prompt="goal")
    assert failed_crawl.succeeded is False

    monkeypatch.setattr(generator, "_call_ai", lambda prompt: (_ for _ in ()).throw(RuntimeError("ai failed")))
    failed_suite = generator.generate(crawl=crawl, prompt="goal")
    assert failed_suite.succeeded is False


def test_web_test_generator_calls_openai_branch(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(generator_module.ConfigManager, "load", lambda: FrameworkConfig())
    generator = WebTestGenerator(ai_config=AIConfig(provider="openai"))
    monkeypatch.setattr(generator_module, "_call_openai", lambda system, user, config: "openai")

    assert generator._call_ai("prompt") == "openai"


def test_web_test_generator_additional_branches(monkeypatch: pytest.MonkeyPatch) -> None:
    anthropic_calls: list[dict[str, object]] = []
    openai_calls: list[dict[str, object]] = []

    class FakeAnthropic:
        def __init__(self, api_key: str, timeout: int) -> None:
            self.messages = SimpleNamespace(create=self.create)

        def create(self, **kwargs: object) -> object:
            anthropic_calls.append(kwargs)
            return SimpleNamespace(content=[SimpleNamespace(text="anthropic code")])

    class FakeOpenAI:
        def __init__(self, api_key: str, timeout: int) -> None:
            self.chat = SimpleNamespace(completions=SimpleNamespace(create=self.create))

        def create(self, **kwargs: object) -> object:
            openai_calls.append(kwargs)
            return SimpleNamespace(choices=[SimpleNamespace(message=SimpleNamespace(content="openai code"))])

    monkeypatch.setattr(generator_module.anthropic, "Anthropic", FakeAnthropic)
    monkeypatch.setattr(generator_module.openai, "OpenAI", FakeOpenAI)
    assert _call_anthropic("sys", "user", AIConfig(anthropic_api_key="k")) == "anthropic code"
    assert _call_openai("sys", "user", AIConfig(provider="openai", openai_api_key="k")) == "openai code"
    assert anthropic_calls and openai_calls

    summary = _build_crawl_summary(CrawlResult(url="https://example.com"))
    assert "TITLE: (no title)" in summary
    assert "META DESCRIPTION: (none)" in summary
    external_only_summary = _build_crawl_summary(
        CrawlResult(
            url="https://example.com",
            links=[LinkElement(text="External", href="https://other.com", is_external=True)],
        )
    )
    assert "INTERNAL LINKS" not in external_only_summary

    parsed = _parse_tests_from_code("def helper() -> None:\n    pass\n")
    assert parsed[0].name == "test_generated_suite"

    monkeypatch.setattr(generator_module.ConfigManager, "load", lambda: FrameworkConfig())
    anthropic_generator = WebTestGenerator(ai_config=AIConfig(anthropic_api_key="x", provider="anthropic"))
    monkeypatch.setattr(
        generator_module,
        "_call_anthropic",
        lambda system, user, config: "anthropic",
    )
    assert anthropic_generator._call_ai("prompt") == "anthropic"

    generator = WebTestGenerator(ai_config=AIConfig())
    monkeypatch.setattr(
        generator,
        "_call_ai",
        lambda prompt: "```python\ndef test_ok(page: Page) -> None:\n    page.goto(BASE_URL)\n```",
    )
    suite = generator.generate(CrawlResult(url="https://example.com"), prompt="goal")
    assert suite.succeeded is True
